# Generated by Django 5.2.14 on 2026-05-31 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRecordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('birth_place', models.CharField(max_length=160)),
                ('birth_date', models.DateField()),
                ('identity_document', models.FileField(upload_to='criminal_records/ids/')),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('review', 'En verification'), ('approved', 'Approuvee'), ('delivered', 'Delivree'), ('rejected', 'Rejetee')], default='submitted', max_length=30)),
                ('secure_pdf', models.FileField(blank=True, upload_to='criminal_records/pdf/')),
                ('qr_code', models.ImageField(blank=True, upload_to='criminal_records/qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
