# Generated by Django 5.2.14 on 2026-05-31 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('diploma', 'Diplome'), ('attestation', 'Attestation'), ('certificate', 'Certificat'), ('transcript', 'Releve de notes'), ('admin', 'Document administratif')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='documents/uploads/')),
                ('unique_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('review', 'Verification'), ('approved', 'Valide'), ('rejected', 'Rejete')], default='submitted', max_length=30)),
                ('qr_code', models.ImageField(blank=True, upload_to='documents/qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
