# Generated by Django 5.2.14 on 2026-05-22 13:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_osinstallation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom_client', models.CharField(max_length=160)),
                ('telephone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('new', 'Nouvelle'), ('confirmed', 'Confirmee'), ('delivered', 'Livree'), ('cancelled', 'Annulee')], default='new', max_length=20)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='operations.product')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
