# Generated by Django 5.2.14 on 2026-05-31 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('trainer', 'Formateur'), ('client', 'Client'), ('student', 'Etudiant')], default='client', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telephone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('organization', models.CharField(blank=True, max_length=160, verbose_name='organisation')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA activee')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
