# Generated by assistant to add language field to Profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(default="fr", max_length=10, choices=[('fr', 'Français'), ('en', 'English')], verbose_name='langue'),
        ),
    ]
