# Generated by Django 6.0.5 on 2026-05-26 16:27

import connect.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CriminalRecordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(editable=False, max_length=36, unique=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=180)),
                ('motif', models.CharField(blank=True, max_length=180)),
                ('statut', models.CharField(choices=[('new', 'Nouvelle'), ('review', 'En revue'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='new', max_length=20)),
                ('paiement', models.CharField(choices=[('unpaid', 'Non payé'), ('pending', 'En attente'), ('paid', 'Payé')], default='unpaid', max_length=20)),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to=connect.models.upload_document_path)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casier_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(editable=False, max_length=36, unique=True)),
                ('titre', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=connect.models.upload_document_path)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('processed', 'Traitée')], default='submitted', max_length=20)),
                ('verification_code', models.CharField(blank=True, editable=False, max_length=128)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=connect.models.upload_qr_path)),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to=connect.models.upload_document_path)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('agent_legalisation', 'Agent de légalisation'), ('agent_authentification', "Agent d'authentification"), ('agent_casier', 'Service de casier judiciaire'), ('citizen', 'Citoyen')], default='citizen', max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('organisation', models.CharField(blank=True, max_length=180)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
