# Generated by Django 5.2.14 on 2026-05-22 11:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=160)),
                ('telephone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=180)),
                ('categorie', models.CharField(choices=[('laptop', 'Ordinateur portable'), ('desktop', 'Ordinateur de bureau'), ('printer', 'Imprimante'), ('accessory', 'Accessoire'), ('storage', 'Disque dur'), ('antivirus', 'Antivirus')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='AntivirusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('marque', models.CharField(choices=[('kaspersky', 'Kaspersky'), ('avast', 'Avast'), ('eset', 'ESET NOD32'), ('bitdefender', 'Bitdefender')], max_length=30)),
                ('cle_licence', models.CharField(blank=True, max_length=120)),
                ('date_activation', models.DateField(default=django.utils.timezone.localdate)),
                ('date_expiration', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.client')),
            ],
            options={
                'ordering': ['date_expiration'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('appareil', models.CharField(max_length=180)),
                ('numero_serie', models.CharField(blank=True, max_length=120)),
                ('service', models.CharField(choices=[('formatage', 'Formatage'), ('windows', 'Reinstallation Windows'), ('hardware', 'Reparation materielle'), ('cleaning', 'Nettoyage logiciel'), ('update', 'Mise a jour systeme')], max_length=40)),
                ('panne_declaree', models.TextField()),
                ('diagnostic', models.TextField(blank=True)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('received', 'Recu'), ('in_progress', 'En reparation'), ('done', 'Termine'), ('delivered', 'Livre')], default='received', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='operations.client')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='NetworkIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_intervention', models.CharField(choices=[('installation', 'Installation reseau'), ('routeur', 'Configuration routeur'), ('partage', 'Partage de connexion'), ('surveillance', 'Surveillance reseau'), ('maintenance', 'Maintenance reseau')], max_length=40)),
                ('technologies', models.CharField(help_text='Ex: RJ45, Wi-Fi, Switch, Routeur', max_length=255)),
                ('description', models.TextField()),
                ('date_intervention', models.DateField(default=django.utils.timezone.localdate)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('terminee', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.client')),
            ],
            options={
                'ordering': ['-date_intervention'],
            },
        ),
        migrations.CreateModel(
            name='OSInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('appareil', models.CharField(max_length=180)),
                ('systeme', models.CharField(choices=[('windows_11', 'Windows 11'), ('windows_10', 'Windows 10'), ('ubuntu', 'Ubuntu'), ('linux_mint', 'Linux Mint')], max_length=30)),
                ('licence_fournie', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField()),
                ('cout_journalier', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('active', 'En cours'), ('returned', 'Retourne'), ('late', 'En retard')], default='active', max_length=20)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='operations.client')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.product')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payee', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='operations.client')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.product')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='operations.sale')),
            ],
        ),
    ]
