# Generated by Django 5.2.14 on 2026-05-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osinstallation',
            options={'ordering': ['-cree_le']},
        ),
    ]
