# Generated by Django 5.2.14 on 2026-05-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_product_image_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='moyen_paiement',
            field=models.CharField(choices=[('cash', 'Paiement a la livraison'), ('orange_money', 'Orange Money')], default='cash', max_length=30),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='numero_orange_money',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='reference_orange_money',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='statut_paiement',
            field=models.CharField(choices=[('unpaid', 'Non paye'), ('pending', 'En attente de verification'), ('paid', 'Paye'), ('failed', 'Echec')], default='unpaid', max_length=30),
        ),
    ]
