# Generated by Django 5.2.14 on 2026-05-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_customerorder_moyen_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_externe',
            field=models.URLField(blank=True),
        ),
    ]
