# Generated by Django 5.2.14 on 2026-05-31 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic_signature', models.CharField(blank=True, max_length=255)),
                ('legalized_file', models.FileField(blank=True, upload_to='legalization/files/')),
                ('legalized_at', models.DateTimeField(blank=True, null=True)),
                ('public_enabled', models.BooleanField(default=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legalization', to='documents.documentrequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
